### ISSUE TITLE
minor questions on starting and stopping server

### ISSUE THREAD

**Issue by airscottdenning** [rickbassham/ekos-web#3]
Rick -- I got everything installed and running. Excellent packaging and documentation!

Thank you very much for this.

Do you start the server automatically and log its output? Or just using 'node.js index' at command line each time? 

Is the proper way to stop the server just to ^C the process in the terminal?

**Comment by rickbassham** [comment]
Yeah, I start it automatically with docker.

Just change `ubuntu` to the user name you normally run under.

`/etc/systemd/system/ekos-web.service`

```
[Unit]
Description=ekos-web

[Service]
Type=simple
User=ubuntu
ExecStart=docker run -p 3000:3000 --rm ekos-web
Restart=always

[Install]
WantedBy=multi-user.target
```

**Comment by rickbassham** [comment]
And yes, you can just `ctrl-c` in the terminal to stop it.

**Comment by airscottdenning** [comment]
I can run manually but my systemd service won't start. 

Here's the output of systemctl status ekos-web:
âekos-web.service - ekos-web
     Loaded: loaded (/etc/systemd/system/ekos-web.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sun 2020-11-29 07:16:49 MST; 679ms ago
    Process: 4921 ExecStart=/snap/bin/docker run -p 3000:3000 --rm ekos-web (code=exited, status=126)
   Main PID: 4921 (code=exited, status=126)

Nov 29 07:16:49 mpi systemd[1]: ekos-web.service: Scheduled restart job, restart counter is at 5.
Nov 29 07:16:49 mpi systemd[1]: Stopped ekos-web.
Nov 29 07:16:50 mpi systemd[1]: ekos-web.service: Start request repeated too quickly.
Nov 29 07:16:50 mpi systemd[1]: ekos-web.service: Failed with result 'exit-code'.
Nov 29 07:16:50 mpi systemd[1]: Failed to start ekos-web.

============

Here's the content of my /etc/systemd/system/ekos-web.service:

[Unit]
Description=ekos-web

[Service]
Type=simple
User=denning
ExecStart=/snap/bin/docker run -p 3000:3000 --rm ekos-web
Restart=always

[Install]
WantedBy=multi-user.target

=============

If I try to start by hand using the command in the service file I get permission denied

mpi:~ $ /snap/bin/docker run -p 3000:3000 --rm ekos-web
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.

But this command works fine as sudo

Maybe this has to run as root (or ubuntu)?

**Comment by rickbassham** [comment]
https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user

You need to add your user to the docker group.

**Comment by airscottdenning** [comment]
Ah thank you! That makes sense.

Working correctly now. 

Appreciate all your help!

**Comment by airscottdenning** [comment]
Hi Rick, I've updated ekos-web and now I can't get the systemd service to start anymore. 

Runs fine interactively but systemctl status ekos-web returns the following:

● ekos-web.service - ekos-web
     Loaded: loaded (/etc/systemd/system/ekos-web.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sun 2020-12-27 22:42:23 MST; 1min 6s ago
    Process: 1555 ExecStart=/usr/bin/docker run -p 3000:3000 -it rickbassham/ekos-web:latest (code=exited, status=1/FAILURE)
   Main PID: 1555 (code=exited, status=1/FAILURE)

Dec 27 22:42:23 u1 systemd[1]: ekos-web.service: Main process exited, code=exited, status=1/FAILURE
Dec 27 22:42:23 u1 systemd[1]: ekos-web.service: Failed with result 'exit-code'.
Dec 27 22:42:23 u1 systemd[1]: ekos-web.service: Scheduled restart job, restart counter is at 10.
Dec 27 22:42:23 u1 systemd[1]: Stopped ekos-web.
Dec 27 22:42:23 u1 systemd[1]: ekos-web.service: Start request repeated too quickly.
Dec 27 22:42:23 u1 systemd[1]: ekos-web.service: Failed with result 'exit-code'.
Dec 27 22:42:23 u1 systemd[1]: Failed to start ekos-web.

Thanks for any advice. 

Scott

**Comment by airscottdenning** [comment]
BTW I *do* belong to group docker:

u1:~ $ groups
denning adm dialout cdrom sudo dip plugdev netdev lpadmin lxd sambashare docker

**Comment by rickbassham** [comment]
Looks like you've updated your systemd service file. What does it look like now? Also, what system are you running on? Can you post the output of `uname -a` and `cat /etc/os.release`?

**Comment by airscottdenning** [comment]
Indeed this is also a new machine — AMD64 mini computer. Also trying to run reliably on a pi4 with ubuntu 20.04

> On Dec 28, 2020, at 6:06 AM, Rick Bassham <notifications@github.com> wrote:
> Looks like you've updated your systemd service file. What does it look like now? Also, what system are you running on? Can you post the output of uname -a and cat /etc/os.release?
> 
Here’s my /etc/systemd/system/ekos-web.service file

u1:~ $ cat /etc/systemd/system/ekos-web.service 
[Unit]
Description=ekos-web

[Service]
Type=simple
User=denning
ExecStart=/usr/bin/docker run -p 3000:3000 -it rickbassham/ekos-web:latest
Restart=always

[Install]
WantedBy=multi-user.target

==========

Here’s my system information:

u1:~ $ uname -a
Linux u1 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

u1:~ $ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by rickbassham** [comment]
And the output if you manually run?

```
/usr/bin/docker run -p 3000:3000 -it rickbassham/ekos-web:latest
```

**Comment by rickbassham** [comment]
Ok, I was able to reproduce it. Change your `ExecStart` line to the following:

```
ExecStart=/usr/bin/docker run -p 3000:3000 --rm rickbassham/ekos-web:latest
```

You can't use the `-it` flags in systemd, as then it expects a terminal.

Then run:

```
sudo systemctl daemon-reload
sudo systemctl restart ekos-web
```

It should be running then.

**Comment by airscottdenning** [comment]
No Immediate output when I run manually … it just works!

When I start Ekos and fire up Ekos Live the terminal window prints

u1:~ $ /usr/bin/docker run -p 3000:3000 -it rickbassham/ekos-web:latest
request started /api/authenticate
upgrade started /message/ekos?username&token=TOKEN&email&from_date&to_date&plan_id&type
upgrade started /media/ekos?username&token=TOKEN&email&from_date&to_date&plan_id&type
upgrade started /cloud/ekos?username&token=TOKEN&email&from_date&to_date&plan_id&type

**Comment by airscottdenning** [comment]
Sure enough — now starts with my system just fine. 

Many thanks — resolved now!
